version: '3.8'

services:
  sh:
    build:
      context: ./sh
    container_name: sh_img
    environment:
      DEBUG: False
    ports:
      - "8001:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  nginx:
    image: nginx:latest
    container_name: nginx_img
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - media_volume:/media
    ports:
      - "80:80"
    depends_on:
      - sh

volumes:
  static_volume:
  media_volume: