# Generated by Django 5.0.2 on 2024-04-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название сети, например: TRC20')),
                ('wallet', models.CharField(max_length=255, verbose_name='Кошелёк:')),
                ('img', models.ImageField(upload_to='qr/wallet/', verbose_name='QR')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'QrUSDT',
                'verbose_name_plural': 'QrUSDT',
            },
        ),
    ]
