# Generated by Django 5.0.2 on 2024-03-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_asic_created_asic_percentages_asic_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asic',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.8, max_digits=4, null=True, verbose_name='Процент скидки: 0.8'),
        ),
        migrations.AlterField(
            model_name='asic',
            name='asic_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Номер асика'),
        ),
        migrations.AlterField(
            model_name='asic',
            name='percentages',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.25, max_digits=4, null=True, verbose_name='Различие дохода в процентах, пример: 0.8'),
        ),
        migrations.AlterField(
            model_name='asicdescription',
            name='el',
            field=models.TextField(verbose_name='Какую криптовалюту можно добывать'),
        ),
        migrations.AlterField(
            model_name='asicdescription',
            name='our',
            field=models.TextField(verbose_name='О товаре'),
        ),
        migrations.AlterField(
            model_name='asicdescription',
            name='protect',
            field=models.TextField(verbose_name='Особенности оборудования'),
        ),
        migrations.AlterField(
            model_name='property',
            name='elect_ef',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Энергоэффективность, пример: 48 J/TH'),
        ),
    ]
