# Generated by Django 5.0.2 on 2024-03-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_asic_percent_alter_asic_asic_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asic',
            name='back_card',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Задний фон для карты, пример: #000'),
        ),
        migrations.AddField(
            model_name='asic',
            name='back_th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Задний фон для TH/s, пример: #000'),
        ),
        migrations.AddField(
            model_name='asic',
            name='color_th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет текста TH/s, пример: #000'),
        ),
        migrations.AddField(
            model_name='asic',
            name='text_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет текста, пример: #000'),
        ),
    ]
