# Generated by Django 5.0.2 on 2024-03-10 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_asic_back_card_asic_back_th_asic_color_th_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsicPopularBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Основной цвет, пример: синий')),
                ('back_card', models.CharField(blank=True, max_length=255, null=True, verbose_name='Задний фон для карты, пример: #000')),
                ('text_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет текста, пример: #000')),
                ('back_th', models.CharField(blank=True, max_length=255, null=True, verbose_name='Задний фон для TH/s, пример: #000')),
                ('color_th', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет текста TH/s, пример: #000')),
            ],
            options={
                'verbose_name': 'Задний фон',
                'verbose_name_plural': 'Задний фон',
            },
        ),
        migrations.AddField(
            model_name='asic',
            name='bg_fon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cat.asicpopularbg', verbose_name='ЗАДНИЙ ФОН'),
        ),
    ]
