# Generated by Django 5.0.2 on 2024-03-10 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_asicpopularbg_asic_bg_fon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asic',
            name='bg_fon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cat.asicpopularbg', verbose_name='ЗАДНИЙ ФОН'),
        ),
    ]
