# Generated by Django 5.0.2 on 2024-04-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0007_asic_faovarit'),
    ]

    operations = [
        migrations.AddField(
            model_name='asicbrand',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='brand_light/', verbose_name='Фото TELEGRAM для бренда(svg)'),
        ),
    ]
