# Generated by Django 5.0.2 on 2024-04-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0008_asicbrand_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='asic',
            name='usdt',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена в USDT'),
        ),
    ]
