# Generated by Django 5.0.2 on 2024-04-15 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0010_productcategory_stabilizer_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='StabilizerBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название бренда')),
                ('image', models.FileField(blank=True, upload_to='stabilizer/brand/', verbose_name='Фото если надо')),
                ('show_title', models.CharField(blank=True, max_length=255, verbose_name='Отображаемое название если надо')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Бренд Стабилизатора',
                'verbose_name_plural': 'Бренды Стабилизаторов',
            },
        ),
        migrations.CreateModel(
            name='StabilizerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название стабилизатора')),
                ('img', models.FileField(upload_to='stabilizer/dop_photo/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Доп фото стабилизатора',
                'verbose_name_plural': 'Доп фото стабилизатора',
            },
        ),
        migrations.CreateModel(
            name='StabilizerProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название характеристики')),
                ('description', models.CharField(max_length=255, verbose_name='Описание характеристики')),
            ],
            options={
                'verbose_name': 'Описание стабилизатора',
                'verbose_name_plural': 'Описание стабилизатора',
            },
        ),
        migrations.AlterModelOptions(
            name='stabilizer',
            options={'verbose_name': 'Стабилизатор', 'verbose_name_plural': 'Стабилизаторы'},
        ),
        migrations.RemoveField(
            model_name='stabilizer',
            name='unique_property',
        ),
        migrations.AddField(
            model_name='stabilizer',
            name='main_img',
            field=models.ImageField(null=True, upload_to='stabilizer/', verbose_name='Главное фото'),
        ),
        migrations.AddField(
            model_name='stabilizer',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='stabilizer',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='stabilizer',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat.stabilizerbrand', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='stabilizer',
            name='add_photo',
            field=models.ManyToManyField(blank=True, to='cat.stabilizerimage', verbose_name='Дополнительные фото'),
        ),
        migrations.AddField(
            model_name='stabilizer',
            name='st_property',
            field=models.ManyToManyField(to='cat.stabilizerproperty', verbose_name='Характеристики'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
