# Generated by Django 5.0.2 on 2024-04-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0011_stabilizerbrand_stabilizerimage_stabilizerproperty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stabilizer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
