# Generated by Django 5.0.6 on 2024-06-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0013_phase_stabilizer_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='asic',
            name='grivn_calc',
            field=models.DecimalField(decimal_places=5, default=0.305, max_digits=10, verbose_name='Процент для перевода в гривны'),
        ),
        migrations.AlterField(
            model_name='stabilizer',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
