# Generated by Django 5.0.6 on 2024-06-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0015_asicdescription_our_en_asicdescription_our_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asicdescription',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='asicdescription',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='asicdescription',
            name='title_uk',
        ),
        migrations.AddField(
            model_name='asicdescription',
            name='el_en',
            field=models.TextField(null=True, verbose_name='Какую криптовалюту можно добывать'),
        ),
        migrations.AddField(
            model_name='asicdescription',
            name='el_ru',
            field=models.TextField(null=True, verbose_name='Какую криптовалюту можно добывать'),
        ),
        migrations.AddField(
            model_name='asicdescription',
            name='el_uk',
            field=models.TextField(null=True, verbose_name='Какую криптовалюту можно добывать'),
        ),
        migrations.AddField(
            model_name='asicdescription',
            name='firm_en',
            field=models.TextField(null=True, verbose_name='О производителе'),
        ),
        migrations.AddField(
            model_name='asicdescription',
            name='firm_ru',
            field=models.TextField(null=True, verbose_name='О производителе'),
        ),
        migrations.AddField(
            model_name='asicdescription',
            name='firm_uk',
            field=models.TextField(null=True, verbose_name='О производителе'),
        ),
        migrations.AddField(
            model_name='asicdescription',
            name='protect_en',
            field=models.TextField(null=True, verbose_name='Особенности оборудования'),
        ),
        migrations.AddField(
            model_name='asicdescription',
            name='protect_ru',
            field=models.TextField(null=True, verbose_name='Особенности оборудования'),
        ),
        migrations.AddField(
            model_name='asicdescription',
            name='protect_uk',
            field=models.TextField(null=True, verbose_name='Особенности оборудования'),
        ),
    ]
