# Generated by Django 5.0.6 on 2024-06-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0016_remove_asicdescription_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cold_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Охлаждение'),
        ),
        migrations.AddField(
            model_name='property',
            name='cold_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Охлаждение'),
        ),
        migrations.AddField(
            model_name='property',
            name='cold_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Охлаждение'),
        ),
        migrations.AddField(
            model_name='property',
            name='power_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Источник питания'),
        ),
        migrations.AddField(
            model_name='property',
            name='power_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Источник питания'),
        ),
        migrations.AddField(
            model_name='property',
            name='power_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Источник питания'),
        ),
    ]
