# Generated by Django 5.0.2 on 2024-03-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя автора')),
                ('description', models.TextField(verbose_name='Текст комментария')),
                ('link_name', models.CharField(max_length=255, verbose_name='Имя аккаунта, пример: @dimadayn')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на аккаунт, пример: https://tme/dimadayn')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='SvgImgSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_slide', models.PositiveIntegerField(default=0, verbose_name='Номер слайда')),
                ('svg', models.FileField(upload_to='', verbose_name='Svg для слайда')),
            ],
            options={
                'verbose_name': 'Svg для слайда',
                'verbose_name_plural': 'Svg для слайда',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Главный текст слайда')),
                ('description', models.TextField(verbose_name='Описание слайда')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет текста, пример: #000')),
                ('bg_color', models.CharField(max_length=255, verbose_name='Цвет слайда, пример: #000')),
                ('number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Номер слайда')),
                ('main_page', models.BooleanField(default=False, verbose_name='Отображается на главной странице')),
                ('bg_hover_btn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет при наведение на кнопку')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('svg_img', models.ManyToManyField(to='main_sh.svgimgslide', verbose_name='Svg картинки для слайда, максимум 6')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
