# Generated by Django 5.0.2 on 2024-03-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='svgimgslide',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер фото слайда'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='svg_img',
            field=models.ManyToManyField(to='main_sh.svgimgslide', verbose_name='Svg картинки для слайда, максимум 5'),
        ),
    ]
