# Generated by Django 5.0.2 on 2024-03-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sh', '0002_svgimgslide_title_alter_slide_svg_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='slide_main_photo/', verbose_name='Главное фото'),
        ),
    ]
