# Generated by Django 5.0.2 on 2024-03-22 02:38

import django.db.models.deletion
import main_sh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sh', '0005_alter_blognews_managers_orderlot_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Для какого заказа, пример: Для заказа 1')),
                ('art', models.CharField(default=main_sh.models.generate_random_string, max_length=9, verbose_name='Номер гарантии')),
                ('ready', models.BooleanField(default=False, verbose_name='Заказ получили')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_sh.order', verbose_name='Какой заказ')),
            ],
            options={
                'verbose_name': 'Гарантия',
                'verbose_name_plural': 'Гарантии',
            },
        ),
    ]
