# Generated by Django 5.0.2 on 2024-03-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sh', '0006_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('num', models.CharField(max_length=3)),
            ],
        ),
    ]
