# Generated by Django 5.0.2 on 2024-03-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sh', '0008_truststeps_alter_aboutsteps_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Номер картинки')),
                ('img', models.ImageField(upload_to='about_slider/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотки',
            },
        ),
    ]
