# Generated by Django 5.0.2 on 2024-04-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sh', '0009_photolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_way', models.CharField(choices=[('usdt_self', 'USDT (оплатить самостоятельно)'), ('usdt_manager', 'USDT (оплатить с менеджером)'), ('card', 'На карту'), ('cash', 'Наличными')], max_length=100)),
                ('get_way', models.CharField(choices=[('office_pickup', 'Самовывоз из офиса в Москве'), ('delivery', 'Доставка')], max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
