# Generated by Django 5.0.2 on 2024-04-08 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sh', '0010_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_sh.shipping', verbose_name='Информация по доставке'),
        ),
    ]
