# Generated by Django 5.0.2 on 2024-04-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sh', '0012_order_total_price_alter_shipping_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlot',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
