# Generated by Django 5.0.2 on 2024-04-09 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0008_asicbrand_svg'),
        ('main_sh', '0014_alter_order_order_number_alter_order_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlot',
            name='asic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.asic', verbose_name='Асик для лота'),
        ),
    ]
