# Generated by Django 5.0.2 on 2024-04-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sh', '0016_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
