# Generated by Django 5.0.2 on 2024-04-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sh', '0017_application_payed'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название шага')),
                ('step_number', models.PositiveIntegerField(default=1, verbose_name='Номер шага')),
                ('description', models.TextField(verbose_name='Описание шага')),
                ('img', models.ImageField(upload_to='order_steps/', verbose_name='Фото для шага')),
                ('step_class', models.CharField(max_length=255, verbose_name='Класс для шага, пример: step__item1')),
                ('timer', models.PositiveIntegerField(default=5, verbose_name='Время в минутах')),
            ],
            options={
                'verbose_name': 'Шаг',
                'verbose_name_plural': 'Шаги',
            },
        ),
    ]
