# Generated by Django 5.0.6 on 2024-06-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sh', '0019_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='truststeps',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='truststeps',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='truststeps',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='truststeps',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truststeps',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truststeps',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
