# Generated by Django 5.0.6 on 2024-06-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sh', '0020_truststeps_description_en_truststeps_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsteps',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsteps',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsteps',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsteps',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsteps',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsteps',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blognews',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание новости'),
        ),
        migrations.AddField(
            model_name='blognews',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание новости'),
        ),
        migrations.AddField(
            model_name='blognews',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание новости'),
        ),
        migrations.AddField(
            model_name='blognews',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок новости'),
        ),
        migrations.AddField(
            model_name='blognews',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок новости'),
        ),
        migrations.AddField(
            model_name='blognews',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок новости'),
        ),
        migrations.AddField(
            model_name='blogparagraph',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст абзаца'),
        ),
        migrations.AddField(
            model_name='blogparagraph',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст абзаца'),
        ),
        migrations.AddField(
            model_name='blogparagraph',
            name='text_uk',
            field=models.TextField(null=True, verbose_name='Текст абзаца'),
        ),
        migrations.AddField(
            model_name='blogparagraph',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок абзаца'),
        ),
        migrations.AddField(
            model_name='blogparagraph',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок абзаца'),
        ),
        migrations.AddField(
            model_name='blogparagraph',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок абзаца'),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='ordersteps',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание шага'),
        ),
        migrations.AddField(
            model_name='ordersteps',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание шага'),
        ),
        migrations.AddField(
            model_name='ordersteps',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание шага'),
        ),
        migrations.AddField(
            model_name='ordersteps',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название шага'),
        ),
        migrations.AddField(
            model_name='ordersteps',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название шага'),
        ),
        migrations.AddField(
            model_name='ordersteps',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название шага'),
        ),
        migrations.AddField(
            model_name='slide',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание слайда'),
        ),
        migrations.AddField(
            model_name='slide',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание слайда'),
        ),
        migrations.AddField(
            model_name='slide',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание слайда'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Главный текст слайда'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Главный текст слайда'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Главный текст слайда'),
        ),
    ]
