# Generated by Django 5.0.6 on 2024-06-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sh', '0021_aboutsteps_description_en_aboutsteps_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractParagraphPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст пункта')),
                ('text_en', models.TextField(null=True, verbose_name='Текст пункта')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст пункта')),
                ('text_uk', models.TextField(null=True, verbose_name='Текст пункта')),
                ('number', models.PositiveIntegerField(verbose_name='Номер пункта')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункты',
            },
        ),
        migrations.CreateModel(
            name='ContractParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название параграфа')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название параграфа')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название параграфа')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Название параграфа')),
                ('paragraph_number', models.PositiveIntegerField(verbose_name='Номер параграфа')),
                ('point', models.ManyToManyField(to='main_sh.contractparagraphpoint', verbose_name='Пункт параграфа')),
            ],
            options={
                'verbose_name': 'Параграф',
                'verbose_name_plural': 'Параграфы',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название договора')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название договора')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название договора')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Название договора')),
                ('contract_number', models.PositiveIntegerField(verbose_name='Номер договора')),
                ('paragraph', models.ManyToManyField(to='main_sh.contractparagraph', verbose_name='Параграф')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
    ]
