# Generated by Django 5.0.6 on 2024-06-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sh', '0022_contractparagraphpoint_contractparagraph_contracts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blognews',
            options={'ordering': ['-created'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='contractparagraph',
            options={'ordering': ['paragraph_number'], 'verbose_name': 'Параграф', 'verbose_name_plural': 'Параграфы'},
        ),
        migrations.AlterField(
            model_name='blognews',
            name='created',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
